name: Smoke test the library

on:
  schedule:
    - cron: '0 0 * * 0' # weekly on Sundays
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  smoke_tests:
    strategy:
      fail-fast: false
      matrix:
        py_version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py_version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install deps
      run: pip install -U -e .[n2]
      if: runner.os != "Windows"
    - name: Install deps without n2
      run: pip install -U -e .
      if: runner.os = "Windows"
    - name: Run renderers on examples
      run: |
        cd examples
        python render.py
